# The ExternalName service is a special type of Kubernetes service 
# that provides DNS-level redirection to external services outside your cluster, without proxying or load balancing.

#   Feature	                                 Description
# No Selector	                   Doesn't target pods (unlike ClusterIP/NodePort)
# DNS-Level Only	               No network proxying occurs
# Works with Any DNS	           Can point to services in other clouds, on-prem, or the internet
# Namespace Isolation	           Follows normal Kubernetes namespace rules

# ✅ Integrating with external databases (AWS RDS, Cloud SQL)
# ✅ Connecting to legacy systems outside Kubernetes
# ✅ Simplifying service migration (abstract external dependencies)
# ✅ Mocking external services in development
# ❌ Not for load balancing (use ClusterIP + Endpoints instead)
# ❌ No traffic control (can't add retries, timeouts, etc.)


apiVersion: v1
kind: Service
metadata:
  name: simple-external-service
spec:
  type: ExternalName
  externalName: my.database.example.com