# A NodePort service is one of the ways to expose your Kubernetes application externally.
# It opens a static port on each worker node's IP address, allowing traffic to be routed to your pods.

# Assigns a Static Port (30000-32767 by default) on every node in the cluster.
# Routes Traffic from <NodeIP>:<NodePort> → Service Port → Pod TargetPort.
# Uses kube-proxy to manage iptables/ipvs rules for load balancing.

# ✅ Local Development (Minikube, Kind, bare-metal clusters).
# ✅ Testing before setting up a LoadBalancer.
# ✅ On-Prem Kubernetes where cloud load balancers aren’t available.
# ❌ Avoid in Production (Use LoadBalancer or Ingress instead).

# This file defines a Kubernetes Service of type NodePort for an application labeled "nodeport".
# It specifies the port that the service will expose and the target port on the pods.
# This service will allow external traffic to access the application running in the pods.
apiVersion: v1
kind: Service
metadata:
  name: simple-nodeport
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007