apiVersion: v1
kind: Pod
metadata:
  name: hostpath-volume-pod
spec:
  containers:
  - name: hostpath-volume-pod
    image: nginx
    volumeMounts:
    - mountPath: /foo
      name: hostpath-volume
      readOnly: true
  volumes:
  - name: hostpath-volume
    # mount /tmp, but only if that directory already exists
    hostPath:
      path: /tmp # directory location on host