# hostPath volumes mount a file or directory from the host node's filesystem into your pod.
# Unlike emptyDir, this isn't temporary—it persists even after pod deletion (but only on that specific node).

#                   When to Use hostPath?
# ✅ Debugging/development (accessing host logs, binaries).
# ✅ Node-specific data (e.g., accessing Docker internals, host certificates).
# ✅ Single-node clusters (not recommended for production multi-node clusters). 
# ❌ Not for persistent storage (use PersistentVolume instead).
# ❌ Dangerous in production (bypasses Kubernetes storage management).

#                  When Not to Use hostPath
# Multi-node clusters → Use PersistentVolume.
# User data storage → Risk of data loss if node fails.
# Untrusted pods → Security risk.

#                  Dangers & Pitfalls
# 1. Node Affinity Required
# If the pod restarts on a different node, the hostPath won’t have the expected data.
# Fix: Use nodeSelector to pin pods to specific nodes.

# 2. Security Risks
# Pods can read/write host system files (e.g., modify /etc).
# Fix: Use readOnly: true and restrict with PodSecurityPolicy.

# 3. No Isolation
# Multiple pods writing to the same hostPath can corrupt data.


apiVersion: v1                              # API version for the Kubernetes object
kind: Pod                                   # Type of Kubernetes object
metadata:                                   # Metadata for the pod
  name: hostpath-volume-pod                 # Name of the pod 
spec:                                       # Specification for the pod 
  containers:                               # List of containers in the pod       
  - name: hostpath-volume-pod               # Name of the container
    image: nginx                            # Image for the container 
    volumeMounts:                           # Volume mounts for the container  
    - mountPath: /foo                       # Path in the container where the volume is mounted 
      name: hostpath-volume                 # Name of the volume to mount
      readOnly: true                        # Mount the volume as read-only 
  volumes:                                  # List of volumes for the pod    
  - name: hostpath-volume                   # Name of the volume
    # mount /tmp, but only if that directory already exists
    hostPath:                               # Type of volume, hostPath indicates a volume from the host's filesystem       
      path: /tmp # directory location on host