apiVersion: v1                
kind: Pod                     
metadata:                     
  name: nginx-pod
  labels:
    env: development
    tier: frontend
spec:                       
  containers:
  - image: nginx              
    name: nginx-container    
    ports:            
    - containerPort: 80      
      protocol: TCP