# A ReplicationController (RC) is an older Kubernetes object that ensures a specified number of pod replicas are running at all times.
# ✅ Maintains Desired Pod Count – If pods crash or are deleted, the RC replaces them.
# ✅ Scaling Up/Down – You can increase or decrease the number of replicas.
# ✅ Self-Healing – Automatically restarts failed pods.
# ❌ RC uses exact label matching (equality-based selectors)
# ❌ Does not support rolling updates (use Deployments for that).
# ❌ Limited to managing pods only, not other resources like services or volumes.
# Note: ReplicationControllers are largely replaced by Deployments in modern Kubernetes, but they are still useful for understanding basic concepts.

apiVersion: v1                  # The API version for the ReplicationController
kind: ReplicationController     # The kind of Kubernetes object, in this case, a ReplicationController
metadata:                       # Metadata about the ReplicationController 
  name: nginx                   # Name of the ReplicationController 
spec:                           # Specification for the ReplicationController
  replicas: 4                   # Desired number of pod replicas
  selector:                     # Selector to identify the pods managed by this RC   
    app: nginx                  # Label selector to match pods with label "app: nginx"
  template:                     # Template for the pods that this RC will manage
    metadata:                   # Metadata for the pod template
      name: nginx               # Name of the pod template
      labels:                   # Labels for the pod template
        app: nginx              # Label to match the pods with the selector
    spec:                       # Specification for the pod
      containers:               # List of containers in the pod  
      - name: nginx             # Name of the container    
        image: nginx            # Docker image for the container  
        ports:                  # Ports exposed by the container
        - containerPort: 80     # Port number on which the container listens


