apiVersion: v1                # specifies the API version
kind: Namespace               # defines the kind of resource
metadata:                     # metadata for the namespace 
  name: application           # name of the namespace
---                           # Separator for the next resource
apiVersion: v1                # specifies the API version 
kind: Pod                     # defines the kind of resource 
metadata:                     # metadata for the pod
  name: apache-pod            # name of the pod 
  namespace: application      # namespace where the pod will be created
  labels:                     # labels for the pod
    app: apache               # label key-value pair
spec:                         # specification for the pod
  containers:                 # list of containers in the pod
    - name: apache-container  # name of the container
      image: httpd:2.4        # image to be used for the container
      ports:                  # ports to be exposed by the container
        - containerPort: 80   # port number to be exposed
