apiVersion: v1                                                    # specifies the API version
kind: Pod                                                         # defines the kind of resource
metadata:                                                         # metadata for the pod    
  name: pi                                                        # name of the pod
spec:                                                             # specification for the pod
  containers:                                                     # list of containers in the pod
  - name: pi                                                      # name of the container
    image: perl:5.34.0                                            # image to be used for the container
    command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(5000)"] # command to run in the container
  restartPolicy: Never                                            # restart policy for the pod 