apiVersion: v1                
kind: Namespace               
metadata:                     
  name: cloud-engineering      
---
apiVersion: v1                 
kind: ServiceAccount          
metadata:                       
  name: cloud-engineers            
  namespace: cloud-engineering  

---                             
apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-app
  namespace: cloud-engineering
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal-app
  template:
    metadata:
      labels:
        app: internal-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80         
