apiVersion: v1                            # specifies the API version     
kind: Namespace                           # defines the kind of resource
metadata:                                 # metadata for the namespace    
  name: cloud-engineering                 # name of the namespace 
---
apiVersion: v1                            # specifies the API version  
kind: ServiceAccount                      # defines the kind of resource
metadata:                                 # metadata for the service account  
  name: cloud-engineers                   # name of the service account 
  namespace: cloud-engineering            # namespace where the service account will be created

---                             
apiVersion: apps/v1                       # specifies the API version
kind: Deployment                          # defines the kind of resource
metadata:                                 # metadata for the deployment
  name: internal-app                      # name of the deployment
  namespace: cloud-engineering            # namespace where the deployment will be created
spec:                                     # specification for the deployment 
  replicas: 1                             # number of replicas for the deployment
  selector:                               # selector for the deployment
    matchLabels:                          # labels to match for the deployment
      app: internal-app                   # label key-value pair
  template:                               # template for the pod
    metadata:                             # metadata for the pod
      labels:                             # labels for the pod  
        app: internal-app                 # label key-value pair
    spec:                                 # specification for the pod
      containers:                         # list of containers in the pod
      - name: nginx                       # name of the container
        image: nginx:alpine               # image to be used for the container
        ports:                            # ports to be exposed by the container  
        - containerPort: 80               # port number to be exposed
